#pragma config(Motor,  motorA,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorD,          RightM,        tmotorEV3_Large, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	* 3 square challenge
	* Pro Team
	* Drive around square 3 times
	*/
	backward(1, rotations, 50); //* Move forwars 1 rotation at half max *//
	turnLeft(360, degrees, 25);
}
