#pragma config(Sensor, S1,     Gyrosense,      sensorEV3_Gyro)
#pragma config(Motor,  motorA,          LeftM,         tmotorEV3_Large, openLoop, driveLeft, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorD,          RightM,        tmotorEV3_Large, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	* 3 square challenge
	* Pro Team
	* Drive around square 3 times
	* 3.4cm wheel radius
	*/
	resetGyro(Gyrosense);
	repeat(12)
  {
  	  forward(3.21, rotations, 50);
			while(getGyroDegrees(Gyrosense)>= -90)
      	{
  	  				turnLeft(2.5, degrees, 25);
      	}
			resetGyro(Gyrosense);
  }

}
