#pragma config(Sensor, S1,     GyroSense,      sensorEV3_Gyro)
#pragma config(Sensor, S4,     ColorSense,     sensorEV3_Color)
#pragma config(Motor,  motorA,          LeftM,         tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorD,          RightM,        tmotorEV3_Large, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	/*
	* 3 square challenge
	* Pro Team
	* Drive around square 3 times
	*/
	repeat(forever)
  {
    lineTrackLeft(ColorSense, 38, -50, 0);
    //*backward(3, rotations, 50);
		//*setMotor(motorA, 25);
  	//*setMotor(motorD, -25);
  	//*wait(1, seconds);
  	//*stopAllMotors();
  }

}
