#pragma config(Sensor, S1,     Gyrosense,      sensorEV3_Gyro)
#pragma config(Motor,  motorA,          LeftMot,       tmotorEV3_Large, PIDControl, driveLeft, encoder)
#pragma config(Motor,  motorB,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorC,           ,             tmotorEV3_Large, openLoop)
#pragma config(Motor,  motorD,          RightMot,      tmotorEV3_Large, PIDControl, driveRight, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	float radius;
	radius = 3.175;
	//Wheel maths//
	float circum;
	circum = 19.949;

	forward(43.18/circum, rotations, 50); //17 inches, first forward//
	//first 90 turn//
	//12 inches, second forward//

}
